# A string used to distinguish different Supabase projects on the same machine.
# Not required if you have a single project.
project_id = "emprendimientoscr"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
# public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version_num;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost:54321"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 2500
# pop3_port = 1100

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "https://www.costaricaemprende.com"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["http://localhost:3000", "https://www.costaricaemprende.com"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true
# Allow/disallow anonymous sign-ins to your project.
enable_anonymous_sign_ins = false
# Allow/disallow testing manual linking of accounts
enable_manual_linking = false

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses.
# If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false
# If enabled, users will need to reauthenticate or have logged in recently to change their password.
secure_password_change = false
# Template for authentication emails
[auth.email.template.invite]
subject = "Has sido invitado a Emprendimientos CR"
content_path = "./supabase/templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirma tu cuenta en Emprendimientos CR"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Restablece tu contraseña - Emprendimientos CR"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.email_change]
subject = "Confirma tu nuevo email - Emprendimientos CR"
content_path = "./supabase/templates/email_change.html"

[auth.email.template.magic_link]
subject = "Tu enlace de acceso a Emprendimientos CR"
content_path = "./supabase/templates/magic_link.html"

[auth.email.template.reauthentication]
subject = "Confirma tu identidad - Emprendimientos CR"
content_path = "./supabase/templates/reauthentication.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false
# Template for authentication SMS messages
[auth.sms.template.signup]
content = "Tu código de confirmación es {{ .Code }}"
[auth.sms.template.invite]
content = "Has sido invitado a unirte {{ .SiteURL }}"
[auth.sms.template.recovery]
content = "Tu código de recuperación es {{ .Code }}"

# Use pre-defined map of claims
[auth.jwt]
aud = "authenticated"
exp = 3600
iss = "supabase"

[auth.jwt.default_group_email_domains]
# A list of email domains that should be assigned to the default group.
domains = []

[edge_runtime]
# Configure one of the supported poolers. The pooler is used to proxy connections to the database.
enabled = true
# Configure one of the supported poolers. The pooler is used to proxy connections to the database.
ip_version = "ipv4"

[analytics]
enabled = false

[functions]
# A mapping of function slug to import map.
[functions.import_map]
# import_map = "./import_map.json"

[experimental]
# Configures Postgres storage-engine with OrioleDB (S3).
orioledb_version = ""
# Configures S3 bucket used by OrioleDB.
s3_host = "localhost"
s3_region = "local"
s3_access_key = ""
s3_secret_key = ""